# -*- coding: UTF-8 -*-


def show_usage():
    print(r"+-----------------------------------------------------------------------------------------------+")
    print(r"| >->> Download ordered online *.ts videos using mode -d and arguments below.                   |")
    print(r"| [script] [mode_1 <-d>] [url] [max_limit <int>] [download max_threads <int>]                   |")
    print(r"| e.g.: online_video.py -d http(s)://www.test.com/videos/temp/xOAgLH9076000.ts 617 10           |")
    print(r"+-----------------------------------------------------------------------------------------------+")
    print(r"| >->> Download specified online *.ts videos using mode -sd and arguments below.                |")
    print(r"| [script] [mode_2 <-sd>] [url] [index array <int[]>] [download max_threads <int>]              |")
    print(r"| e.g.: online_video.py -sd http(s)://tmp.com/videos/xOAgLH9076000.ts [13,23,44,139,...] 10     |")
    print(r"+-----------------------------------------------------------------------------------------------+")
    print(r"| >->> Download ordered AES encrypted online *.ts videos using mode -ad and arguments below.    |")
    print(r"| [script] [mode_3 <-ad>] [url] [max_limit <int>] [AES key] [download max_threads <int>]        |")
    print(r"| e.g.: online_video.py -ad http(s)://www.test.com/xOAgLH9076000.ts 864 912342018ea9a9ca 10     |")
    print(r"+-----------------------------------------------------------------------------------------------+")
    print(r"| >->> Download specified AES encrypted online *.ts videos using mode -sad and arguments below. |")
    print(r"| [script] [mode_4 <-sad>] [url] [index array <int[]>] [AES key] [download max_threads <int>]   |")
    print(r"| e.g.: online_video.py -sad http(s)://tmp.com/xOAgLH9076000.ts [13,23,...] 912342018ea9a9ca 10 |")
    print(r"+-----------------------------------------------------------------------------------------------+")
    print(r"| >->> Download unordered online *.ts videos using mode -u and arguments below.                 |")
    print(r"| [script] [mode_5 <-u>] [url left part] [m3u8 file] [download max_threads <int>]               |")
    print(r"| e.g.: online_video.py -u http(s)://www.test.com/hls/ D:\Downloads\index.m3u8 10               |")
    print(r"+-----------------------------------------------------------------------------------------------+")
    print(r"| >->> Download specified online *.ts videos using mode -su and arguments below.                |")
    print(r"| [script] [mode_6 <-su>] [log file] [download max_threads <int>]                               |")
    print(r"| e.g.: online_video.py -su D:\Downloads\crawler\online_video.log 10                            |")
    print(r"+-----------------------------------------------------------------------------------------------+")
    print(r"| >->> Download unordered AES encrypted online *.ts videos using mode -au and arguments below.  |")
    print(r"| [script] [mode_7 <-au>] [url left part] [m3u8 file] [AES key] [download max_threads <int>]    |")
    print(r"| e.g.: online_video.py -au http(s)://www.test.com/ D:\Downloads\index.m3u8 912342018ea9a9ca 10 |")
    print(r"+-----------------------------------------------------------------------------------------------+")
    print(r"| >->> Download specified AES encrypted online *.ts videos using mode -sau and arguments below. |")
    print(r"| [script] [mode_8 <-sau>] [log file] [AES key] [download max_threads <int>]                    |")
    print(r"| e.g.: online_video.py -sau D:\Downloads\crawler\online_video.log 912342018ea9a9ca 10          |")
    print(r"+-----------------------------------------------------------------------------------------------+")
